### ISSUE TITLE
Things to work out

### ISSUE THREAD

**Issue by asbjornh** [Creuna-Oslo/prop-types-csharp-webpack-plugin#1]
### isRequired

Is there any way of indicating this in C#?

### node, element, func and instanceOf

We can probably just strip these

### Client only props

There are several kinds of prop that doesn't really make sense to expose. Things like theming props and state being passed down the component tree. This likely won't be a problem for components at the very top of the tree, but stuff like buttons, links, popups, forms and inputs might definitely have stuff like this.

We might need a mechanism for choosing what components or props to include in C# classes.

### PropTypes.oneOf

What do we do when the array provided to `PropTypes.oneOf` is imported from an external file?

### PropTypes.oneOfType

This seems like a bad idea to have in a C# class. We should probably have some validation when parsing propTypes.

**Comment by pellebjerkestrand** [comment]
`isRequired` ➡️ `[Required]`.

See https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.requiredattribute(v=vs.110).aspx

**Comment by asbjornh** [comment]
The example at the bottom of the page is `[Required()]`. Did I miss something?

**Comment by pellebjerkestrand** [comment]
I don't remember if `[Required]` is OK when you don't have any parameters or not or if `[Required()]` is required (😛), but that's an easy thing to fix/change.

**Comment by asbjornh** [comment]
Idea from @pellebjerkestrand :

```
const Component = ({ ... }) => <div />;

Component.propTypes = {
  a: PropTypes.string,
  b: PropTypes.bool,
  c: PropTypes.func
};

Component.excludedPropTypes = {
  c
};
```

**Comment by asbjornh** [comment]
PropTypes.oneOfType: Can we use generics?

**Comment by asbjornh** [comment]
And what about `PropTypes.number`? Do we have to choose int or float?

**Comment by pellebjerkestrand** [comment]
Maybe `untransformedPropTypes` is more understandable `excludedPropTypes`. If not, something that has a bit better semantics than "excluded", IMO.

With regards to `number`: what if we do `int` by default, rename `excludedPropTypes` to something like `propTypesMeta` where the value can be metadata that indicates how the prop type should be handled (`exclude` to exclude, `float` to choose float instead of int etc.)?

**Comment by asbjornh** [comment]
I like that!

**Comment by Reasonable-Solutions** [comment]
Int by default sounds awfully awkward. the Javascript numerical types are just 64bit doubles and Int -> Float is always(idk about csharp) a safe cast.

**Comment by asbjornh** [comment]
Closing this as everything here but `PropTypes.oneOfType` has been dealt with. Created #11 for oneOfType
