### ISSUE TITLE
using System.Collections.Generic

### ISSUE THREAD

**Issue by Sriess** [Creuna-Oslo/prop-types-csharp-webpack-plugin#6]
https://github.com/Creuna-Oslo/prop-types-csharp-webpack-plugin/blob/9c478e9539f7bf7342abf37b3e7d4670a21d7693/source/utils/generate-csharp.js#L13

If this using is for IList, then it should be `using System.Collections.Generic;`

**Comment by asbjornh** [comment]
But you told me that System.Collections was correct last time! 😮 

I'll fix
